export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';

export const SET_INGREDIENT = 'SET_INGREDIENT';
export const FETCH_INGREDIENT_FAILED = 'FETCH_INGREDIENT_FAILED';

export const SENDING_ORDER_START = 'SENDING_ORDER_START';
export const SENDING_ORDER_SUCCEED = 'SENDING_ORDER_SUCCEED';
export const SENDING_ORDER_FAILED = 'SENDING_ORDER_FAILED';

export const RESET_ALL = 'RESET_ALL';